apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pod-q2
  name: pod-q2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod-q2
status:
  loadBalancer: {}
