apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: q23-ns
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - env
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          key: special.how
          name: special-config
    image: k8s.gcr.io/busybox
    name: test-container
  restartPolicy: Never
