apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: q23-ns
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 600
    - env 
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          key: special.how
          name: special-config
  restartPolicy: Never
