apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-q31
  name: pod-q31
spec:
  containers:
  - image: nginx
    name: pod-q31
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
