apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  labels:
    app: dns
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    imagePullPolicy: IfNotPresent
    name: dnsutils
  restartPolicy: Always
