apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-nginx-q15
  name: pod-nginx-q15
spec:
  containers:
  - image: nginx
    name: pod-nginx-q15
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
