apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dns
  name: svc-dnsutils-q15
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dns
status:
  loadBalancer: {}
