apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-busybox
  name: deploy-busybox
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
