apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-busybox
  name: deploy-busybox
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
status: {}
