apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pod-nginx-q14
  name: pod-nginx-q14
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod-nginx-q14
status:
  loadBalancer: {}
