apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-nginx-q21
  name: pod-nginx-q21
spec:
  containers:
  - image: nginx
    name: pod-nginx-q21
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
