apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: q22-ns
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: workdir
  dnsPolicy: Default
  initContainers:
  - command:
    - wget
    - -O
    - /work-dir/index.html
    - http://info.cern.ch
    image: busybox
    name: install
    volumeMounts:
    - mountPath: /work-dir
      name: workdir
  volumes:
  - emptyDir: {}
    name: workdir
