apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: q18-ns
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
