apiVersion: v1
kind: PersistentVolume
metadata:
    name: grande-pv
spec:
    capacity:
      storage: 4Gi
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /opt/diversos
      server: 172.31.44.232
      readOnly: false
