apiVersion: v1
kind: PersistentVolume
metadata:
    name: medio-pv
spec:
    capacity:
      storage: 2Gi
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /opt/diversos
      server: 172.31.44.232
      readOnly: false
