apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
  namespace: q24-ns
spec:
  containers:
  - env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          key: backend-username
          name: backend-user
    image: nginx
    name: envars-test-container
