apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pods-q3-deployment
  name: pods-q3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pods-q3-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: pods-q3-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
