apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-q1
  name: pod-q1
  namespace: q1-ns
spec:
  containers:
  - image: nginx
    name: pod-q1
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: volume-nao-persistente
  volumes:
  - name: volume-nao-persistente
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
