apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-q1
  name: pod-q1
  namespace: q1_ns
spec:
  containers:
  - image: nginx
    name: pod-q1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
